### ISSUE TITLE
[Bug]: Undefined variable $getLocale

### ISSUE THREAD

**Issue by MegdadFadaee** [mokhosh/filament-jalali#13]
### What happened?

after i update the packages to last version i get "Undefined variable $getLocale ".

### How to reproduce the bug

i thing its just missing from blade.
you can check full debug error from hear:
[https://flareapp.io/share/W7z3AE85](https://flareapp.io/share/W7z3AE85)
thanks.

### Package Version

3.5.0

### PHP Version

8.3.0

### Laravel Version

11.11.1

**Comment by mokhosh** [comment]
I couldn't reproduce this issue.
Please provide a reproduction repo.

**Comment by mokhosh** [comment]
You have locked your Filament version to `v3.2.57`.
Upgrading `filament/filament` to the latest version will solve your issue. Current version is `v3.2.110`.

Do this is your `composer.json`:
```diff
- "filament/filament": "3.2.57",
+ "filament/filament": "^3.0",
```
