### ISSUE TITLE
[Enhancement]: نمایش تاریخ به اعداد فارسی و انگلیسی

### ISSUE THREAD

**Issue by Mo0rteza** [mokhosh/filament-jalali#15]
### What happened?

اگه بشه که اعداد رو به صورت فارسی و انگلیسی نمایش داد خوب میشه. یعنی خواستیم تاریخ رو به صورت فارسی نشون بدیم نخواستیم هم به انگلیسی یه پراپرتی یا متغیر یا ... رو ست کرد و اعمال بشه. 

![2](https://github.com/user-attachments/assets/da1d2b1c-b6de-4e4a-92e6-c466f8a3a522)

### How to reproduce the bug

مطابق عکس میخوام تاریخ به صورت اعداد فارسی نمایش داده بشه تا شکل جدول یک دست باشه. سایر ستون ها با اضافه کردن متد numeric() خودشون به صورت فارسی نمایش داده میشه. البته که locale='fa' هستش.
من تگ feature رو نتونستم برای issue ست کنم. بی زحمت لیبل رو هم عوض کنید.

### Package Version

3.5.0

### PHP Version

8.2

### Laravel Version

11.9

### Which operating systems does with happen with?

Windows

**Comment by mokhosh** [comment]
ممنونم از پیشنهادتون.
توی نسخه بعدی سعی میکنم اضافه کنم.

**Comment by mokhosh** [comment]
Done in https://github.com/mokhosh/filament-jalali/releases/tag/v4.2.0
