### ISSUE TITLE
[Bug]: Undefine variable $getLocale error

### ISSUE THREAD

**Issue by MuhammadKazimSadiq** [mokhosh/filament-jalali#17]
### What happened?

<img width="766" alt="image" src="https://github.com/user-attachments/assets/e34e4150-e732-4797-ae85-351c790566b4">

### How to reproduce the bug

when navigating to a page using jalali components

### Package Version

4.3

### PHP Version

8.1

### Laravel Version

10.48

**Comment by mokhosh** [comment]
See #12 #13 #14
