### ISSUE TITLE
[Enhancement ]: پلاگین برای rangedatepicker

### ISSUE THREAD

**Issue by amoopoori** [mokhosh/filament-jalali#19]
### What happened?

سلام اول اینکه خیلی ممنون واقعا همه چی عالیه
بهترین پلاگینی که برای rangedatepicker پیدا کردم تو فیلامنت این بود:
https://filamentphp.com/plugins/malzariey-daterangepicker-filter
میخواستم ببینم راهی هست بتونم این رو جلالی کنم؟

### How to reproduce the bug

سلام اول اینکه خیلی ممنون واقعا همه چی عالیه
بهترین پلاگینی که برای rangedatepicker پیدا کردم تو فیلامنت این بود:
https://filamentphp.com/plugins/malzariey-daterangepicker-filter
میخواستم ببینم راهی هست بتونم این رو جلالی کنم؟

### Package Version

2.0.0

### PHP Version

8.2.0

### Laravel Version

9.0.0

### Which operating systems does with happen with?

Windows

**Comment by mokhosh** [comment]
سلام عزیز جان.
اصلش اینه که باید تغییرات لازم رو توی js همون پلاگین بدی. نگاه کردم از jquery و moment.js استفاده میکنه و یه پلاگین خاص jquery.
حتما پلاگین جلالی برای moment هست. اون رو احتمالا باید اضافه کنی، بعد ببینی چه تغییراتی توی کد plugin و view نیازه برای تمیز کردن کار.
اینا که حل شد دیگه فقط باید view ی این کامپوننت رو override کنی و تمام.

اگر کارای jquery و moment رو انجام دادی و تو مراحل بعدی سوالی داشتی بهم بگو.

**Comment by amoopoori** [comment]
واقعا پوزش میخوام که باز مزاحم میشم
یه سوال پیش اومده برام نتونستم جوابشو پیدا کنم
ببینید تونستم تمام داکیومنت های moment-jalali(پکیج جلالی شده moment) رو
اعمال کنم
حالا سوالم شاید مسخره ولی نمیدونم چه جوری به پلاگین تنظیمات جدید رو اعمال
کنم
یعنی مثلا باید دستور npm run dev بزنم واگه آره باید تو چه دایرکتوری ای بزنم؟
من فایل های js پلاگین رو حتی وقتی پاک هم میکنم باز هیچ تغییری تو صفحه
نمیبینم
اگر لینک آموزشی هم باشه برام بفرستید میبینم که مزاحمتون نشم

**Comment by amoopoori** [comment]
مهندس جان فهمیدم باید چی کار کنم
ببخشید خیلی پیام دادم:D

**Comment by amoopoori** [comment]
مهندس جان به طور کامل انجام شد و نتیجه نهایی خیلی خوب شد
ممنون بابت راهنماییتون

**Comment by mokhosh** [comment]
عالیه

پیشنهاد میکنم یه پلاگین فیلامنتش کنی
حتما افراد زیادی ازش استفاده میکنن

**Comment by amoopoori** [comment]
تجربه ی این کار رو ندارم
ولی تلاش میکنم انجام بدم

**Comment by mokhosh** [comment]
یه نگاه اینجا بکن.
https://filamentphp.com/docs/3.x/support/plugins/getting-started

هر جاش سوالی داشتی بگو در خدمتم.

**Comment by pooriajahedi** [comment]
@amoopoori سلام دوست عزیز

امکانش هست کدتو به اشتراک بزاری
