### ISSUE TITLE
[Bug]: The names of the months are not fully displayed due to space limitations

### ISSUE THREAD

**Issue by fatehiman** [mokhosh/filament-jalali#20]
### What happened?

![image](https://github.com/user-attachments/assets/27db8c8c-7d8d-4c4b-a8ba-d80ca48c2e48)
As shown in the picture, the full month name is not displayed. It should appear as 'آبان,' but only 'آبا' is visible.
I am using the default theme of Filament 3 without any custom styles.
I believe there might be some default CSS and styling issues.

### How to reproduce the bug

The bug exists by default.

### Package Version

4.4.0

### PHP Version

8.2.0

### Laravel Version

11

### Which operating systems does with happen with?

Linux

**Comment by mokhosh** [comment]
It's not a css issue. It's the default datetime format.

Please check the readme on how to "Configure the Format Globally".

**Comment by mokhosh** [comment]
Here's an example repo, I'm gonna put it here as it's related to this question:

https://github.com/mokhosh/filament-jalali-example

**Comment by afsharmn** [comment]
> Here's an example repo, I'm gonna put it here as it's related to this question:
> 
> https://github.com/mokhosh/filament-jalali-example

you did not use Forms\Components\DatePicker in this app???

i have same problem ...

i also need to change format

how can i do that?

**Comment by mokhosh** [comment]
@afsharmn You can simply do this in a provider like `AppServiceProvider`

```php
Table::$defaultDateDisplayFormat = 'Y/m/d';
DateTimePicker::$defaultDateDisplayFormat = 'Y/m/d';
DateTimePicker::$defaultDateTimeDisplayFormat = 'Y/m/d H:i';
DateTimePicker::$defaultDateTimeWithSecondsDisplayFormat = 'Y/m/d H:i:s';
```
