### ISSUE TITLE
[Bug]: text entry doesnt work

### ISSUE THREAD

**Issue by MuhammadKazimSadiq** [mokhosh/filament-jalali#3]
### What happened?

i get this error when trying to use textentry on infolist:

Illuminate\ Contracts \Container \BindingResolutionException
Unresolvable dependency resolving [Parameter #0 [ <required> string $name ]] in class Filament\Tables\Columns\Column

### How to reproduce the bug

-

### Package Version

3.2

### PHP Version

8.1

### Laravel Version

10

**Comment by mokhosh** [comment]
Fixed in v3.2.1. Thanks for reporting!
